app:
  build: .
  ports:
    - "9000:3000"
  environment:
    - NODE_ENV=production
    - PORT=3000
  links:
    - "db:db"

db:
  image: postgres
  environment:
    - POSTGRES_PASSWORD=superSecretP4ssw0rd
